# Time Series Data Visualization {.unnumbered}


```{r}
#| code-fold: true
#| code-summary: 'Importing Libraries'
#| warning: false
#| output: false
library(tidyverse)
library(ggplot2)
library(forecast)
library(astsa) 
library(xts)
library(tseries)
library(fpp2)
library(fma)
library(lubridate)
library(tidyverse)
library(TSstudio)
library(quantmod)
library(tidyquant)
library(plotly)
library(ggplot2)
library(imputeTS)
library(gridExtra)
library(reticulate)
library(readxl)
#use_python("/usr/local/bin/python3", require = T)
knitr::knit_engines$set(python = reticulate::eng_python)
#py_install("tensorflow")
```





::: panel-tabset

## Data Visualization with Stock Data

The following graph shows overall trends in American Express, Coca Cola and Johnson & Johnshon stock prices.

```{r }
#| warning: false
#| code-fold: true


options("getSymbols.warning4.0"=FALSE)
options("getSymbols.yahoo.warning"=FALSE)

tickers = c("AXP","KO","JNJ" )
for (i in tickers){
  getSymbols(i,
             from = "2012-10-01",
             to = "2024-01-01")}

x <- list(
  title = "date"
)
y <- list(
  title = "value"
)

stock <- data.frame(AXP$AXP.Adjusted,
                    KO$KO.Adjusted,
                    JNJ$JNJ.Adjusted)


stock <- data.frame(stock,rownames(stock))
colnames(stock) <- append(tickers,'Dates')

stock$date<-as.Date(stock$Dates,"%Y-%m-%d")
#head(stock)

################################################

ggplot(stock, aes(x=date)) +
  geom_line(aes(y=AXP, colour="AXP"))+
  geom_line(aes(y=JNJ, colour="JNJ"))+
  geom_line(aes(y=KO, colour="KO"))+
   labs(
    title = "Stock Prices for the Blue Chip Stocks Companies",
    subtitle = "From 2013-2022",
    x = "Date",
    y = "Adjusted Closing Prices")+
    theme(panel.background = element_rect(fill = "white", colour = "grey50"))+
    guides(colour=guide_legend(title="Blue Chip Companies")) 
```


## XRP Candlestick Plot

```{r}
#| code-fold: true
#| warning: false


#plotly
# candlestick plot


xrp_vals <- getSymbols("XRP-USD",auto.assign = FALSE, from = "2021-09-15",src="yahoo") 
#head(xrp_vals)
#start(xrp_vals)
#end(xrp_vals)

xrp_vals=data.frame(xrp_vals)
xrp_vals <- data.frame(xrp_vals,rownames(xrp_vals))
#head(xrp_vals)

colnames(xrp_vals)[7] = "date"
#head(xrp_vals)

xrp_vals$date<-as.Date(xrp_vals$date,"%Y-%m-%d")
#str(xrp_vals)


df <- tail(xrp_vals, 30)

figc <- df %>% plot_ly(x = ~date, type="candlestick",
          open = ~XRP.USD.Open, close = ~XRP.USD.Close,
          high = ~XRP.USD.High, low = ~XRP.USD.Low) 
figc <- figc %>% layout(title = "Basic Candlestick Chart")

figc
```



## Economic Data with Plotly

Hover over the plot to see the difference.
 
```{r}
#| code-fold: true
#| warning: false

# bring in data
economic_data <- read.csv("../../data/fred_data_lab0/economic_data.csv")


economic_data$date <- as.Date(economic_data$date, format="%d/%m/%Y")


g4 <- ggplot(economic_data, aes(x=date)) +
  geom_line(aes(y=cpi, colour="CPI"), size=1) +  
  geom_line(aes(y=gdp, colour="GDP"), size=1) +
  # format
  scale_colour_manual(values = c("CPI" = "red", "GDP" = "blue")) + 
  labs(
    title = "CPI and GDP Over Time",
    subtitle = "From Start Year to End Year",  
    x = "Date",
    y = "Value") +
  guides(colour=guide_legend(title="Indicators"))


# plot
ggplotly(g4) %>%
  layout(hovermode = "x")



```



:::